In [ ]:
%pip install numpy

In [4]:
import numpy as np

In [5]:
a = np.array(2)

In [6]:
a

array(2)

In [7]:
a.ndim

0

In [8]:
arr = np.array([2,4,6,7,8])

In [9]:
arr

array([2, 4, 6, 7, 8])

In [10]:
arr.ndim

1

In [11]:
mat = np.array([[3,5,7],[5,7,8],[4,7,4]])

In [12]:
mat

array([[3, 5, 7],
       [5, 7, 8],
       [4, 7, 4]])

In [13]:
mat.ndim

2

In [14]:
mat = np.array([[1,3,5],[4,3,5]])

In [15]:
mat

array([[1, 3, 5],
       [4, 3, 5]])

In [16]:
mat.ndim

2

In [17]:
mat.shape

(2, 3)